version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: verbs_api
    restart: always
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flashcards

  app:
    build: ./app
    container_name: verbs_app
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000

volumes:
  mongo_data: